title: 
description:
show_downloads: false
google_analytics:
theme: jekyll-theme-slate


defaults:
  -
    scope:
      path: "ctf/jetty.md" 
    values:
      layout: "jetty"
      title: "Görkem Özkanat |s Jetty CTF"