title: Görkem Özkanat
description:
show_downloads: false
google_analytics:
theme: jekyll-theme-slate


defaults:
  -
    scope:
      path: "ctf/jetty.md" 
    values:
      layout: "jetty"
      title: "| Jetty CTF"
      

defaults:
  -
    scope:
      path: "ctf/dvwa.html" 
    values:
      layout: "dvwa"
      title: "| DVWA"

defaults:
  -
    scope:
      path: "ctf/hacker101.html" 
    values:
      layout: "Hacker101"
      title: "| Hacker101"